### ISSUE TITLE
nice job with the alpha but ...

### ISSUE THREAD

**Issue by ringo32** [fdservices/vpacman#2]
yeah the current 1.3.3 is buggy i think you noticed already ,

see also nice feature in the 1.40 alpha...

but https://i.imgur.com/Dz7yDdo.png when you see installed, what does it mean ?

for me looks like Aur / Alien  that is correct ? Also see 0ad , it is installed  but does not list it. only which from aur / local.. since 0ad also is local basicly but also comes from upstream with pacman.. Stil it should see on availble the version nr as example, it is on 1.3.3 also..  but 1.3.3 does not install anything currently here, it does not see the version but then it ask for full update it start to show version "" installed but upstream is verstion 1.54 as example.

**Comment by AndyM48** [comment]
Installed should show the number of packages installed, both from the repositories and from AUR/Local. From your screenshot it seems that you have only 51 packages installed, which cannot be correct. I suspect that this is a language problem. Running "pacman -Ss" in English shows "package_name [installed]" or "package_name [installed: version#_available]". Can you confirm that in your language it shows " "package_name [???????]" or "package_name [???????: version#_available]"?

If you can confirm then I will update the code to allow for this, which should make it all much clearer  :-)

Thank you for your interest.  Andrew.

**Comment by ringo32** [comment]
is like https://i.imgur.com/xpDv3be.png   libreoffice-still

this is pacman -Qs libreoffice-still  https://gist.github.com/d9481798d701ab2f4dea839139aed040

only i see is the all side is repo + localAur packages thath shows 
this is an aur package : https://i.imgur.com/iTwLR4a.png

it show the version and availble , but locally installed from repo does not do that. Maytby it looking first on repo then local ?  i dont know... like tkpacman has also a button that only local what you gave installed. it seporate on a point.

yeah this package manager reminds me a lot of PacmanXg , also pacmanxg could also a lot system management but has its own tab for pacman-mirrorlist en arch news and editor on pacman.conf. :)

further it tells it is not installed : https://i.imgur.com/iTwLR4a.png   but i do use linux kernel is btw in all of the options above.. the vpacman is completely in english so i dont have those issues. while im dutch :) and those 51 packages are aur packages.

**Comment by AndyM48** [comment]
As I understand it you installed libreoffice-still as a local package. Libreoffice-still is available in the extra repository. Vpacman correctly recognises that this is a locally installed package, checks the AUR for any possible updates from there, and then reports accordingly. Presumably you do not have extra enabled in your repositories? I tried to replicate this by installing a2ps locally:
pacman -Qs a2ps reports `local/a2ps 4.14-8`
pacman -Ss a2ps reports `extra/a2ps 4.14-8 [installed]`
Vpacman recognises this as available from the extra repo. which seems to be correct. 
What is the result if you run  pacman -Qm?

>  tkpacman has also a button that only local what you gave installed

Tools > Install AUR/Local
>  pacmanxg  has its own tab for pacman-mirrorlist

Tools > Update Mirrorlist

> arch news

View > Latest News

> and editor on pacman.conf

I thought that this was too dangerous, but if there is any interest I could add this.

Re: amdvik - vpacman says that this is installed, and that a new version is available (indicated by the "*"). If you downgrade tcl and tk to version 8.6.8.3 you will see the list  in glorious technicolour (see Wiki/News)

**Comment by AndyM48** [comment]
Would you mind testing alpha-2 to see if you now get a correct "installed" list?

**Comment by ringo32** [comment]
https://i.imgur.com/LuJSWtP.png
https://i.imgur.com/Voiv8Jq.png


this looks better ^ ^ 

if you select all you can see what up stream and where you have...

pacman.conf editor is basicly if i think back not so needed, if you make mistakes it only get worse. 

i think you have stuf in what just need, too much is also not good

just strawling and saw this https://i.imgur.com/iJjIRng.png

when in in tools check config it ask some saved configurations files found i type yes.
https://i.imgur.com/iJjIRng.png

normally i use meld and pacdiff self anyway.. heh 

now is not so confusing anymore looks better ^

**Comment by AndyM48** [comment]
Thank you for the feed back. The error was the same cause I'm afraid - a language problem. I have fixed that one, but will now trawl through the code to try to eliminate other, similar problems. It will take a couple of days at least.

**Comment by ringo32** [comment]
thanks :) will see  but now is better then before atleast

**Comment by AndyM48** [comment]
C'est moi! :-)

I have tried to amend all of the language problems. There are some warning messages left which are not so informative, but I cannot help that.

If you have the time, can you please look at alpha-3 and report any and all bugs that you see. I would be most grateful.

Andrew

**Comment by ringo32** [comment]
the Alpha-3 worked the meld differences.  most of the bugs is sorted pretty nice.

i noticed that it doe sometimes sudo -n pacman (xxx) , cannnot replicate it mayby is fixed but is unknown a bit but better to let it role then have issues with putting passw in int but cannot replicate clear is not a big isue anyway :) didnt see in in this so is fine

thank you for making it.

**Comment by AndyM48** [comment]
Vpacman tried to identify the best method for the user to gain elevated privileges. The three options are:
1.  sudo without the need for a password (sudo -n)
2.  sudo with a password required (sudo)
3.  su with the root password. (su -c)

The only reason to us "sudo -n" is to differentiate between options 1. and 2. The -n does nothing since method 1. does not require a password in any case.

Thank you for your help. Please report any other bugs that you find.

**Comment by ringo32** [comment]
will report in the next if something is up :) close it for now.
