### ISSUE TITLE
qterminal command bit changed

### ISSUE THREAD

**Issue by ringo32** [fdservices/vpacman#3]
its pitty but qterminal has changed a bit... so it going to be off 

--title  and --command dont work anymore

its now also --execute  but no title..

seems now  qterminal --name <title> --execute <command>

Greetz ringo

**Comment by AndyM48** [comment]
I am not familiar with qterminal. In the mean time you can use xterm or any of the other listed terminal for vpacman. I will take a look at qterminal

**Comment by AndyM48** [comment]
I can confirm that qterminal seems to work fine with the Terminal String set to:
`qterminal --title <title> --execute <command>`
(select Tools > Options to change it)

I will update the default string for qterminal in the next update.

Thanks for the heads-up
